"""initial schema

Revision ID: 0c06f6f7f3f8
Revises: 
Create Date: 2026-03-24 00:04:59.550358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c06f6f7f3f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_tor', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('freshness_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('current_freshness', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freshness_queue_person_id'), 'freshness_queue', ['person_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=2048), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationship_score', sa.Float(), nullable=False),
    sa.Column('behavioural_risk', sa.Float(), nullable=False),
    sa.Column('darkweb_exposure', sa.Float(), nullable=False),
    sa.Column('default_risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('composite_quality', sa.Float(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_from', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seed_type', sa.String(length=50), nullable=False),
    sa.Column('seed_value', sa.String(length=1024), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('street', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state_province', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('neighbourhood', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('composite_quality', sa.Float(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_person_id'), 'addresses', ['person_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('web_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_channel', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['web_id'], ['webs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_person_id'), 'alerts', ['person_id'], unique=False)
    op.create_index(op.f('ix_alerts_web_id'), 'alerts', ['web_id'], unique=False)
    op.create_table('aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aliases_alias'), 'aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_aliases_person_id'), 'aliases', ['person_id'], unique=False)
    op.create_table('behavioural_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('gambling_score', sa.Float(), nullable=False),
    sa.Column('drug_signal_score', sa.Float(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('violence_score', sa.Float(), nullable=False),
    sa.Column('financial_distress_score', sa.Float(), nullable=False),
    sa.Column('criminal_signal_score', sa.Float(), nullable=False),
    sa.Column('active_hours', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('top_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('languages_used', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sentiment_avg', sa.Float(), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioural_profiles_person_id'), 'behavioural_profiles', ['person_id'], unique=True)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('web_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('seed_identifier', sa.String(length=1024), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('tor_circuit', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['web_id'], ['webs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_person_id'), 'crawl_jobs', ['person_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_web_id'), 'crawl_jobs', ['web_id'], unique=False)
    op.create_table('credit_risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('default_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(length=30), nullable=False),
    sa.Column('gambling_weight', sa.Float(), nullable=False),
    sa.Column('financial_distress_weight', sa.Float(), nullable=False),
    sa.Column('court_judgment_weight', sa.Float(), nullable=False),
    sa.Column('burner_weight', sa.Float(), nullable=False),
    sa.Column('synthetic_identity_weight', sa.Float(), nullable=False),
    sa.Column('darkweb_weight', sa.Float(), nullable=False),
    sa.Column('criminal_weight', sa.Float(), nullable=False),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_risk_assessments_person_id'), 'credit_risk_assessments', ['person_id'], unique=False)
    op.create_table('crypto_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.String(length=50), nullable=True),
    sa.Column('total_volume_usd', sa.Float(), nullable=False),
    sa.Column('mixer_exposure', sa.Boolean(), nullable=False),
    sa.Column('exchange_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_wallets_address'), 'crypto_wallets', ['address'], unique=True)
    op.create_index(op.f('ix_crypto_wallets_person_id'), 'crypto_wallets', ['person_id'], unique=False)
    op.create_table('data_quality_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('old_composite_quality', sa.Float(), nullable=True),
    sa.Column('new_composite_quality', sa.Float(), nullable=False),
    sa.Column('old_freshness', sa.Float(), nullable=True),
    sa.Column('new_freshness', sa.Float(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_log_person_id'), 'data_quality_log', ['person_id'], unique=False)
    op.create_index(op.f('ix_data_quality_log_record_id'), 'data_quality_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_data_quality_log_table_name'), 'data_quality_log', ['table_name'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('composite_quality', sa.Float(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_person_id'), 'education', ['person_id'], unique=False)
    op.create_table('employment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('employer_name', sa.String(length=500), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('estimated_salary_usd', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('composite_quality', sa.Float(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_history_person_id'), 'employment_history', ['person_id'], unique=False)
    op.create_table('identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('normalized_value', sa.String(length=1024), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('composite_quality', sa.Float(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_identifier_type_value')
    )
    op.create_index('ix_identifier_value', 'identifiers', ['value'], unique=False)
    op.create_index(op.f('ix_identifiers_person_id'), 'identifiers', ['person_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_a_id', sa.UUID(), nullable=False),
    sa.Column('person_b_id', sa.UUID(), nullable=False),
    sa.Column('rel_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_a_id', 'person_b_id', 'rel_type', name='uq_relationship')
    )
    op.create_index(op.f('ix_relationships_person_a_id'), 'relationships', ['person_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_person_b_id'), 'relationships', ['person_b_id'], unique=False)
    op.create_table('social_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('follower_count', sa.BigInteger(), nullable=True),
    sa.Column('following_count', sa.BigInteger(), nullable=True),
    sa.Column('post_count', sa.BigInteger(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Float(), nullable=False),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('composite_quality', sa.Float(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_from', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_social_platform_uid')
    )
    op.create_index(op.f('ix_social_profiles_handle'), 'social_profiles', ['handle'], unique=False)
    op.create_index(op.f('ix_social_profiles_person_id'), 'social_profiles', ['person_id'], unique=False)
    op.create_table('watchlist_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('list_name', sa.String(length=255), nullable=False),
    sa.Column('list_type', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_name', sa.String(length=500), nullable=True),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_matches_person_id'), 'watchlist_matches', ['person_id'], unique=False)
    op.create_table('wealth_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('wealth_band', sa.String(length=20), nullable=False),
    sa.Column('income_estimate_usd', sa.Float(), nullable=True),
    sa.Column('net_worth_estimate_usd', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('employer_signal', sa.Float(), nullable=False),
    sa.Column('property_signal', sa.Float(), nullable=False),
    sa.Column('vehicle_signal', sa.Float(), nullable=False),
    sa.Column('travel_signal', sa.Float(), nullable=False),
    sa.Column('crypto_signal', sa.Float(), nullable=False),
    sa.Column('luxury_signal', sa.Float(), nullable=False),
    sa.Column('education_signal', sa.Float(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wealth_assessments_person_id'), 'wealth_assessments', ['person_id'], unique=False)
    op.create_table('web_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('web_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('depth_found', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_id'], ['webs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_memberships_person_id'), 'web_memberships', ['person_id'], unique=False)
    op.create_index(op.f('ix_web_memberships_web_id'), 'web_memberships', ['web_id'], unique=False)
    op.create_table('behavioural_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['behavioural_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioural_signals_profile_id'), 'behavioural_signals', ['profile_id'], unique=False)
    op.create_table('breach_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('identifier_id', sa.UUID(), nullable=True),
    sa.Column('breach_name', sa.String(length=255), nullable=False),
    sa.Column('breach_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('exposed_fields', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('raw_sample', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identifier_id'], ['identifiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_records_person_id'), 'breach_records', ['person_id'], unique=False)
    op.create_table('burner_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier_id', sa.UUID(), nullable=False),
    sa.Column('burner_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('line_type', sa.String(length=30), nullable=True),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('carrier_category', sa.String(length=50), nullable=True),
    sa.Column('is_ported', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_registered', sa.Boolean(), nullable=True),
    sa.Column('telegram_registered', sa.Boolean(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identifier_id'], ['identifiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burner_assessments_identifier_id'), 'burner_assessments', ['identifier_id'], unique=True)
    op.create_table('crawl_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('bytes_received', sa.Integer(), nullable=True),
    sa.Column('tor_exit_ip', sa.String(length=45), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_job_id'), 'crawl_logs', ['job_id'], unique=False)
    op.create_table('crypto_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('counterparty_address', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('block_time', sa.String(length=50), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['crypto_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_transactions_tx_hash'), 'crypto_transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_crypto_transactions_wallet_id'), 'crypto_transactions', ['wallet_id'], unique=False)
    op.create_table('darkweb_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('identifier_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_url_hashed', sa.String(length=64), nullable=True),
    sa.Column('mention_context', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['identifier_id'], ['identifiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_darkweb_mentions_person_id'), 'darkweb_mentions', ['person_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('social_profile_id', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('local_path', sa.String(length=2048), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=2000), nullable=True),
    sa.Column('faces_detected', sa.Integer(), nullable=False),
    sa.Column('face_embeddings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_profile_id'], ['social_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_hash_sha256'), 'media_assets', ['hash_sha256'], unique=False)
    op.create_index(op.f('ix_media_assets_person_id'), 'media_assets', ['person_id'], unique=False)
    op.create_table('relationship_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_score_history_relationship_id'), 'relationship_score_history', ['relationship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_score_history_relationship_id'), table_name='relationship_score_history')
    op.drop_table('relationship_score_history')
    op.drop_index(op.f('ix_media_assets_person_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_hash_sha256'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_darkweb_mentions_person_id'), table_name='darkweb_mentions')
    op.drop_table('darkweb_mentions')
    op.drop_index(op.f('ix_crypto_transactions_wallet_id'), table_name='crypto_transactions')
    op.drop_index(op.f('ix_crypto_transactions_tx_hash'), table_name='crypto_transactions')
    op.drop_table('crypto_transactions')
    op.drop_index(op.f('ix_crawl_logs_job_id'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    op.drop_index(op.f('ix_burner_assessments_identifier_id'), table_name='burner_assessments')
    op.drop_table('burner_assessments')
    op.drop_index(op.f('ix_breach_records_person_id'), table_name='breach_records')
    op.drop_table('breach_records')
    op.drop_index(op.f('ix_behavioural_signals_profile_id'), table_name='behavioural_signals')
    op.drop_table('behavioural_signals')
    op.drop_index(op.f('ix_web_memberships_web_id'), table_name='web_memberships')
    op.drop_index(op.f('ix_web_memberships_person_id'), table_name='web_memberships')
    op.drop_table('web_memberships')
    op.drop_index(op.f('ix_wealth_assessments_person_id'), table_name='wealth_assessments')
    op.drop_table('wealth_assessments')
    op.drop_index(op.f('ix_watchlist_matches_person_id'), table_name='watchlist_matches')
    op.drop_table('watchlist_matches')
    op.drop_index(op.f('ix_social_profiles_person_id'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_handle'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_relationships_person_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_person_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_identifiers_person_id'), table_name='identifiers')
    op.drop_index('ix_identifier_value', table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_index(op.f('ix_employment_history_person_id'), table_name='employment_history')
    op.drop_table('employment_history')
    op.drop_index(op.f('ix_education_person_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_data_quality_log_table_name'), table_name='data_quality_log')
    op.drop_index(op.f('ix_data_quality_log_record_id'), table_name='data_quality_log')
    op.drop_index(op.f('ix_data_quality_log_person_id'), table_name='data_quality_log')
    op.drop_table('data_quality_log')
    op.drop_index(op.f('ix_crypto_wallets_person_id'), table_name='crypto_wallets')
    op.drop_index(op.f('ix_crypto_wallets_address'), table_name='crypto_wallets')
    op.drop_table('crypto_wallets')
    op.drop_index(op.f('ix_credit_risk_assessments_person_id'), table_name='credit_risk_assessments')
    op.drop_table('credit_risk_assessments')
    op.drop_index(op.f('ix_crawl_jobs_web_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_person_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_behavioural_profiles_person_id'), table_name='behavioural_profiles')
    op.drop_table('behavioural_profiles')
    op.drop_index(op.f('ix_aliases_person_id'), table_name='aliases')
    op.drop_index(op.f('ix_aliases_alias'), table_name='aliases')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_alerts_web_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_person_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_addresses_person_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('webs')
    op.drop_table('persons')
    op.drop_index(op.f('ix_freshness_queue_person_id'), table_name='freshness_queue')
    op.drop_table('freshness_queue')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
