"""add property, vehicle, intelligence, compliance, professional, timeline tables + person fields

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
Create Date: 2025-03-25 00:00:00.000000
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = "f6a7b8c9d0e1"
down_revision = "e5f6a7b8c9d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    #  PROPERTIES                                                          #
    # ------------------------------------------------------------------ #
    op.create_table(
        "properties",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("parcel_number", sa.String(100), nullable=True, index=True),
        sa.Column("street_address", sa.String(500), nullable=True),
        sa.Column("city", sa.String(255), nullable=True),
        sa.Column("state", sa.String(100), nullable=True),
        sa.Column("zip_code", sa.String(20), nullable=True),
        sa.Column("county", sa.String(255), nullable=True),
        sa.Column("country", sa.String(100), nullable=False, server_default="US"),
        sa.Column("property_type", sa.String(50), nullable=True),
        sa.Column("sub_type", sa.String(50), nullable=True),
        sa.Column("year_built", sa.Integer, nullable=True),
        sa.Column("sq_ft_living", sa.Integer, nullable=True),
        sa.Column("sq_ft_lot", sa.Integer, nullable=True),
        sa.Column("bedrooms", sa.Integer, nullable=True),
        sa.Column("bathrooms_full", sa.Integer, nullable=True),
        sa.Column("bathrooms_half", sa.Integer, nullable=True),
        sa.Column("stories", sa.Integer, nullable=True),
        sa.Column("garage_spaces", sa.Integer, nullable=True),
        sa.Column("has_pool", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("zoning", sa.String(100), nullable=True),
        sa.Column("land_use_code", sa.String(50), nullable=True),
        sa.Column("school_district", sa.String(255), nullable=True),
        sa.Column("flood_zone", sa.String(50), nullable=True),
        sa.Column("latitude", sa.Float, nullable=True),
        sa.Column("longitude", sa.Float, nullable=True),
        sa.Column("current_assessed_value_usd", sa.Float, nullable=True),
        sa.Column("current_market_value_usd", sa.Float, nullable=True),
        sa.Column("current_tax_annual_usd", sa.Float, nullable=True),
        sa.Column("last_sale_date", sa.Date, nullable=True),
        sa.Column("last_sale_price_usd", sa.Float, nullable=True),
        sa.Column("last_sale_type", sa.String(50), nullable=True),
        sa.Column("owner_name", sa.String(500), nullable=True),
        sa.Column("owner_mailing_address", sa.String(1000), nullable=True),
        sa.Column("is_owner_occupied", sa.Boolean, nullable=True),
        sa.Column("homestead_exemption", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_investment_property", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        # DataQualityMixin
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        # TimestampMixin
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "property_ownership_history",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("property_id", UUID(as_uuid=True), sa.ForeignKey("properties.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("owner_name", sa.String(500), nullable=True),
        sa.Column("owner_type", sa.String(50), nullable=True),
        sa.Column("acquisition_date", sa.Date, nullable=True),
        sa.Column("disposition_date", sa.Date, nullable=True),
        sa.Column("acquisition_price_usd", sa.Float, nullable=True),
        sa.Column("acquisition_type", sa.String(50), nullable=True),
        sa.Column("disposition_price_usd", sa.Float, nullable=True),
        sa.Column("disposition_type", sa.String(50), nullable=True),
        sa.Column("document_number", sa.String(200), nullable=True),
        sa.Column("grantor", sa.String(500), nullable=True),
        sa.Column("grantee", sa.String(500), nullable=True),
        sa.Column("title_company", sa.String(255), nullable=True),
        sa.Column("loan_amount_usd", sa.Float, nullable=True),
        sa.Column("down_payment_usd", sa.Float, nullable=True),
        sa.Column("days_held", sa.Integer, nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "property_valuations",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("property_id", UUID(as_uuid=True), sa.ForeignKey("properties.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("valuation_year", sa.Integer, nullable=True),
        sa.Column("assessed_value_usd", sa.Float, nullable=True),
        sa.Column("assessed_land_value_usd", sa.Float, nullable=True),
        sa.Column("assessed_improvement_value_usd", sa.Float, nullable=True),
        sa.Column("market_value_usd", sa.Float, nullable=True),
        sa.Column("tax_amount_usd", sa.Float, nullable=True),
        sa.Column("tax_rate", sa.Float, nullable=True),
        sa.Column("exemptions", JSONB, nullable=False, server_default="{}"),
        sa.Column("valuation_source", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "property_mortgages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("property_id", UUID(as_uuid=True), sa.ForeignKey("properties.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("lender_name", sa.String(500), nullable=True),
        sa.Column("loan_type", sa.String(50), nullable=True),
        sa.Column("original_loan_amount_usd", sa.Float, nullable=True),
        sa.Column("interest_rate", sa.Float, nullable=True),
        sa.Column("loan_term_months", sa.Integer, nullable=True),
        sa.Column("origination_date", sa.Date, nullable=True),
        sa.Column("maturity_date", sa.Date, nullable=True),
        sa.Column("recording_date", sa.Date, nullable=True),
        sa.Column("instrument_number", sa.String(200), nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("is_delinquent", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("foreclosure_filing_date", sa.Date, nullable=True),
        sa.Column("foreclosure_sale_date", sa.Date, nullable=True),
        sa.Column("payoff_date", sa.Date, nullable=True),
        sa.Column("payoff_amount_usd", sa.Float, nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ------------------------------------------------------------------ #
    #  VEHICLES / AIRCRAFT / VESSELS                                       #
    # ------------------------------------------------------------------ #
    op.create_table(
        "vehicles",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("vin", sa.String(17), nullable=True, index=True),
        sa.Column("make", sa.String(100), nullable=True),
        sa.Column("model", sa.String(100), nullable=True),
        sa.Column("year", sa.Integer, nullable=True),
        sa.Column("trim", sa.String(100), nullable=True),
        sa.Column("body_style", sa.String(50), nullable=True),
        sa.Column("color_exterior", sa.String(50), nullable=True),
        sa.Column("color_interior", sa.String(50), nullable=True),
        sa.Column("engine", sa.String(100), nullable=True),
        sa.Column("transmission", sa.String(50), nullable=True),
        sa.Column("drivetrain", sa.String(50), nullable=True),
        sa.Column("fuel_type", sa.String(50), nullable=True),
        sa.Column("mileage", sa.Integer, nullable=True),
        sa.Column("license_plate", sa.String(50), nullable=True),
        sa.Column("plate_state", sa.String(10), nullable=True),
        sa.Column("registration_state", sa.String(10), nullable=True),
        sa.Column("registration_expiry", sa.Date, nullable=True),
        sa.Column("title_state", sa.String(10), nullable=True),
        sa.Column("title_status", sa.String(50), nullable=True),
        sa.Column("lienholder_name", sa.String(500), nullable=True),
        sa.Column("is_commercial", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_stolen", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("nhtsa_recalls", JSONB, nullable=False, server_default="[]"),
        sa.Column("estimated_value_usd", sa.Float, nullable=True),
        sa.Column("acquisition_date", sa.Date, nullable=True),
        sa.Column("disposition_date", sa.Date, nullable=True),
        sa.Column("acquisition_price_usd", sa.Float, nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "aircraft",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("n_number", sa.String(10), nullable=True, index=True),
        sa.Column("serial_number", sa.String(100), nullable=True),
        sa.Column("manufacturer", sa.String(255), nullable=True),
        sa.Column("model", sa.String(255), nullable=True),
        sa.Column("aircraft_type", sa.String(50), nullable=True),
        sa.Column("engine_type", sa.String(50), nullable=True),
        sa.Column("num_engines", sa.Integer, nullable=True),
        sa.Column("num_seats", sa.Integer, nullable=True),
        sa.Column("year_manufactured", sa.Integer, nullable=True),
        sa.Column("airworthiness_class", sa.String(50), nullable=True),
        sa.Column("registration_date", sa.Date, nullable=True),
        sa.Column("expiration_date", sa.Date, nullable=True),
        sa.Column("last_action_date", sa.Date, nullable=True),
        sa.Column("owner_name", sa.String(500), nullable=True),
        sa.Column("registrant_type", sa.String(50), nullable=True),
        sa.Column("registrant_address", sa.String(1000), nullable=True),
        sa.Column("is_deregistered", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("estimated_value_usd", sa.Float, nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "vessels",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("mmsi", sa.String(20), nullable=True, index=True),
        sa.Column("imo_number", sa.String(20), nullable=True),
        sa.Column("vessel_name", sa.String(255), nullable=True),
        sa.Column("call_sign", sa.String(50), nullable=True),
        sa.Column("flag_country", sa.String(10), nullable=True),
        sa.Column("vessel_type", sa.String(100), nullable=True),
        sa.Column("gross_tonnage", sa.Float, nullable=True),
        sa.Column("length_meters", sa.Float, nullable=True),
        sa.Column("beam_meters", sa.Float, nullable=True),
        sa.Column("draft_meters", sa.Float, nullable=True),
        sa.Column("year_built", sa.Integer, nullable=True),
        sa.Column("builder", sa.String(255), nullable=True),
        sa.Column("owner_name", sa.String(500), nullable=True),
        sa.Column("operator_name", sa.String(500), nullable=True),
        sa.Column("port_of_registry", sa.String(255), nullable=True),
        sa.Column("last_port", sa.String(255), nullable=True),
        sa.Column("destination_port", sa.String(255), nullable=True),
        sa.Column("last_seen_lat", sa.Float, nullable=True),
        sa.Column("last_seen_lon", sa.Float, nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("estimated_value_usd", sa.Float, nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ------------------------------------------------------------------ #
    #  INTELLIGENCE                                                         #
    # ------------------------------------------------------------------ #
    op.create_table(
        "phone_intelligence",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("identifier_id", UUID(as_uuid=True), sa.ForeignKey("identifiers.id", ondelete="CASCADE"), nullable=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("phone_number", sa.String(50), nullable=True),
        sa.Column("carrier_name", sa.String(255), nullable=True),
        sa.Column("carrier_type", sa.String(50), nullable=True),
        sa.Column("line_type", sa.String(50), nullable=True),
        sa.Column("country_code", sa.String(10), nullable=True),
        sa.Column("country_name", sa.String(100), nullable=True),
        sa.Column("area_code", sa.String(10), nullable=True),
        sa.Column("time_zone", sa.String(100), nullable=True),
        sa.Column("is_valid", sa.Boolean, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=True),
        sa.Column("is_ported", sa.Boolean, nullable=True),
        sa.Column("is_prepaid", sa.Boolean, nullable=True),
        sa.Column("is_commercial", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("spam_score", sa.Float, nullable=True),
        sa.Column("fraud_score", sa.Float, nullable=True),
        sa.Column("robocall_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("known_aliases", JSONB, nullable=False, server_default="[]"),
        sa.Column("last_seen_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "email_intelligence",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("identifier_id", UUID(as_uuid=True), sa.ForeignKey("identifiers.id", ondelete="CASCADE"), nullable=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("email_address", sa.String(1024), nullable=True),
        sa.Column("domain", sa.String(500), nullable=True),
        sa.Column("domain_type", sa.String(50), nullable=True),
        sa.Column("provider_name", sa.String(255), nullable=True),
        sa.Column("mx_valid", sa.Boolean, nullable=True),
        sa.Column("smtp_valid", sa.Boolean, nullable=True),
        sa.Column("is_disposable", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_role_address", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_catch_all", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("breach_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("first_seen_breach", sa.Date, nullable=True),
        sa.Column("spam_score", sa.Float, nullable=True),
        sa.Column("fraud_score", sa.Float, nullable=True),
        sa.Column("reputation_score", sa.Float, nullable=True),
        sa.Column("deliverability", sa.String(50), nullable=True),
        sa.Column("platforms_found", JSONB, nullable=False, server_default="[]"),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "ip_intelligence",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("ip_version", sa.Integer, nullable=False, server_default="4"),
        sa.Column("asn", sa.Integer, nullable=True),
        sa.Column("asn_org", sa.String(500), nullable=True),
        sa.Column("isp", sa.String(500), nullable=True),
        sa.Column("organization", sa.String(500), nullable=True),
        sa.Column("country_code", sa.String(10), nullable=True),
        sa.Column("country_name", sa.String(100), nullable=True),
        sa.Column("region", sa.String(255), nullable=True),
        sa.Column("city", sa.String(255), nullable=True),
        sa.Column("latitude", sa.Float, nullable=True),
        sa.Column("longitude", sa.Float, nullable=True),
        sa.Column("time_zone", sa.String(100), nullable=True),
        sa.Column("is_vpn", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_proxy", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_tor", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_datacenter", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_residential", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_mobile", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("threat_type", sa.String(50), nullable=True),
        sa.Column("abuse_score", sa.Float, nullable=True),
        sa.Column("fraud_score", sa.Float, nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ------------------------------------------------------------------ #
    #  COMPLIANCE EXTENDED                                                  #
    # ------------------------------------------------------------------ #
    op.create_table(
        "pep_classifications",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("pep_level", sa.String(20), nullable=True),
        sa.Column("pep_category", sa.String(100), nullable=True),
        sa.Column("position_title", sa.String(500), nullable=True),
        sa.Column("organization", sa.String(500), nullable=True),
        sa.Column("country", sa.String(100), nullable=True),
        sa.Column("jurisdiction", sa.String(255), nullable=True),
        sa.Column("start_date", sa.Date, nullable=True),
        sa.Column("end_date", sa.Date, nullable=True),
        sa.Column("is_current", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("is_former", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("related_to_pep_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True),
        sa.Column("relationship_to_pep", sa.String(100), nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("source_url", sa.String(2048), nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "adverse_media",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("headline", sa.String(2000), nullable=True),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("url", sa.String(2048), nullable=True),
        sa.Column("url_hash", sa.String(64), nullable=True, index=True),
        sa.Column("publication_date", sa.Date, nullable=True),
        sa.Column("source_name", sa.String(255), nullable=True),
        sa.Column("source_country", sa.String(10), nullable=True),
        sa.Column("language", sa.String(20), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("severity", sa.String(20), nullable=False, server_default="medium"),
        sa.Column("sentiment_score", sa.Float, nullable=True),
        sa.Column("is_verified", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_retracted", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("entities_mentioned", JSONB, nullable=False, server_default="[]"),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "shell_company_links",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="SET NULL"), nullable=True, index=True),
        sa.Column("company_name", sa.String(500), nullable=True),
        sa.Column("company_type", sa.String(100), nullable=True),
        sa.Column("jurisdiction", sa.String(255), nullable=True),
        sa.Column("registration_number", sa.String(200), nullable=True),
        sa.Column("incorporation_date", sa.Date, nullable=True),
        sa.Column("dissolution_date", sa.Date, nullable=True),
        sa.Column("role", sa.String(100), nullable=True),
        sa.Column("ownership_pct", sa.Float, nullable=True),
        sa.Column("is_beneficial_owner", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_nominee", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("linked_bank_accounts", JSONB, nullable=False, server_default="[]"),
        sa.Column("linked_properties", JSONB, nullable=False, server_default="[]"),
        sa.Column("source_name", sa.String(255), nullable=True),
        sa.Column("leak_name", sa.String(255), nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ------------------------------------------------------------------ #
    #  PROFESSIONAL                                                         #
    # ------------------------------------------------------------------ #
    op.create_table(
        "professional_licenses",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("license_type", sa.String(200), nullable=True),
        sa.Column("license_number", sa.String(200), nullable=True),
        sa.Column("issuing_body", sa.String(500), nullable=True),
        sa.Column("issuing_state", sa.String(100), nullable=True),
        sa.Column("issuing_country", sa.String(100), nullable=False, server_default="US"),
        sa.Column("issue_date", sa.Date, nullable=True),
        sa.Column("expiry_date", sa.Date, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("is_revoked", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_suspended", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("disciplinary_actions", JSONB, nullable=False, server_default="[]"),
        sa.Column("specializations", JSONB, nullable=False, server_default="[]"),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("verification_url", sa.String(2048), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "corporate_directorships",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("company_name", sa.String(500), nullable=True),
        sa.Column("company_registration", sa.String(200), nullable=True),
        sa.Column("company_jurisdiction", sa.String(255), nullable=True),
        sa.Column("role", sa.String(200), nullable=True),
        sa.Column("is_executive", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_board_member", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("ownership_pct", sa.Float, nullable=True),
        sa.Column("share_count", sa.BigInteger, nullable=True),
        sa.Column("share_value_usd", sa.Float, nullable=True),
        sa.Column("appointment_date", sa.Date, nullable=True),
        sa.Column("resignation_date", sa.Date, nullable=True),
        sa.Column("is_current", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("company_status", sa.String(50), nullable=True),
        sa.Column("company_industry", sa.String(255), nullable=True),
        sa.Column("company_revenue_usd", sa.Float, nullable=True),
        sa.Column("company_employee_count", sa.Integer, nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "military_records",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("branch", sa.String(100), nullable=True),
        sa.Column("country", sa.String(100), nullable=False, server_default="US"),
        sa.Column("rank", sa.String(100), nullable=True),
        sa.Column("rank_grade", sa.String(20), nullable=True),
        sa.Column("service_number", sa.String(100), nullable=True),
        sa.Column("enlistment_date", sa.Date, nullable=True),
        sa.Column("discharge_date", sa.Date, nullable=True),
        sa.Column("discharge_type", sa.String(100), nullable=True),
        sa.Column("mos_afi_nec", sa.String(200), nullable=True),
        sa.Column("deployments", JSONB, nullable=False, server_default="[]"),
        sa.Column("decorations", JSONB, nullable=False, server_default="[]"),
        sa.Column("security_clearance", sa.String(50), nullable=True),
        sa.Column("clearance_status", sa.String(50), nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("source_reliability", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("freshness_score", sa.Float, nullable=False, server_default="1.0"),
        sa.Column("corroboration_count", sa.Integer, nullable=False, server_default="1"),
        sa.Column("corroboration_score", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("conflict_flag", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("verification_status", sa.String, nullable=False, server_default="unverified"),
        sa.Column("composite_quality", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("data_quality", JSONB, nullable=False, server_default="{}"),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scraped_from", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ------------------------------------------------------------------ #
    #  TIMELINE                                                             #
    # ------------------------------------------------------------------ #
    op.create_table(
        "timeline_events",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("event_date", sa.Date, nullable=True),
        sa.Column("event_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_type", sa.String(100), nullable=True),
        sa.Column("title", sa.String(1000), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("location", sa.String(500), nullable=True),
        sa.Column("source_type", sa.String(100), nullable=True),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("source_url_hash", sa.String(64), nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("related_person_ids", JSONB, nullable=False, server_default="[]"),
        sa.Column("related_entity_ids", JSONB, nullable=False, server_default="[]"),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "analyst_assessments",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("analyst_id", sa.String(255), nullable=True),
        sa.Column("assessment_type", sa.String(100), nullable=True),
        sa.Column("overall_risk", sa.String(20), nullable=False, server_default="unknown"),
        sa.Column("risk_score", sa.Float, nullable=True),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("key_findings", JSONB, nullable=False, server_default="[]"),
        sa.Column("red_flags", JSONB, nullable=False, server_default="[]"),
        sa.Column("recommendations", JSONB, nullable=False, server_default="[]"),
        sa.Column("classification_level", sa.String(50), nullable=False, server_default="unclassified"),
        sa.Column("tlp_color", sa.String(20), nullable=False, server_default="white"),
        sa.Column("valid_until", sa.Date, nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "travel_history",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("person_id", UUID(as_uuid=True), sa.ForeignKey("persons.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("departure_country", sa.String(10), nullable=True),
        sa.Column("departure_city", sa.String(255), nullable=True),
        sa.Column("arrival_country", sa.String(10), nullable=True),
        sa.Column("arrival_city", sa.String(255), nullable=True),
        sa.Column("travel_date", sa.Date, nullable=True),
        sa.Column("return_date", sa.Date, nullable=True),
        sa.Column("travel_mode", sa.String(50), nullable=True),
        sa.Column("carrier", sa.String(255), nullable=True),
        sa.Column("flight_number", sa.String(50), nullable=True),
        sa.Column("visa_type", sa.String(100), nullable=True),
        sa.Column("port_of_entry", sa.String(255), nullable=True),
        sa.Column("is_flagged", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("flag_reason", sa.String(500), nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("source_platform", sa.String(100), nullable=True),
        sa.Column("meta", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ------------------------------------------------------------------ #
    #  PERSON TABLE — NEW COLUMNS                                          #
    # ------------------------------------------------------------------ #
    new_person_cols = [
        # Physical
        sa.Column("height_cm", sa.Float, nullable=True),
        sa.Column("weight_kg", sa.Float, nullable=True),
        sa.Column("eye_color", sa.String(30), nullable=True),
        sa.Column("hair_color", sa.String(30), nullable=True),
        sa.Column("hair_length", sa.String(30), nullable=True),
        sa.Column("build", sa.String(50), nullable=True),
        sa.Column("skin_tone", sa.String(50), nullable=True),
        sa.Column("distinguishing_marks", sa.Text, nullable=True),
        # Identity
        sa.Column("place_of_birth", sa.String(500), nullable=True),
        sa.Column("country_of_birth", sa.String(100), nullable=True),
        sa.Column("citizenship_countries", JSONB, nullable=False, server_default="[]"),
        sa.Column("languages_spoken", JSONB, nullable=False, server_default="[]"),
        sa.Column("religion", sa.String(100), nullable=True),
        sa.Column("ethnicity", sa.String(100), nullable=True),
        sa.Column("political_affiliation", sa.String(200), nullable=True),
        sa.Column("marital_status", sa.String(50), nullable=True),
        sa.Column("number_of_children", sa.Integer, nullable=True),
        # Wealth summary
        sa.Column("estimated_net_worth_usd", sa.Float, nullable=True),
        sa.Column("estimated_annual_income_usd", sa.Float, nullable=True),
        sa.Column("wealth_tier", sa.String(50), nullable=True),
        sa.Column("property_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("vehicle_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("aircraft_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("vessel_count", sa.Integer, nullable=False, server_default="0"),
        # Risk/compliance
        sa.Column("pep_status", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("pep_level", sa.String(20), nullable=True),
        sa.Column("is_sanctioned", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("sanctions_lists", JSONB, nullable=False, server_default="[]"),
        sa.Column("adverse_media_score", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("adverse_media_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_deceased", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("date_of_death", sa.Date, nullable=True),
        sa.Column("cause_of_death", sa.String(500), nullable=True),
        # Completeness
        sa.Column("data_completeness_pct", sa.Float, nullable=False, server_default="0.0"),
        sa.Column("last_full_enrichment_at", sa.DateTime(timezone=True), nullable=True),
    ]

    for col in new_person_cols:
        op.add_column("persons", col)


def downgrade() -> None:
    # Remove person columns
    person_new_cols = [
        "height_cm", "weight_kg", "eye_color", "hair_color", "hair_length", "build", "skin_tone",
        "distinguishing_marks", "place_of_birth", "country_of_birth", "citizenship_countries",
        "languages_spoken", "religion", "ethnicity", "political_affiliation", "marital_status",
        "number_of_children", "estimated_net_worth_usd", "estimated_annual_income_usd", "wealth_tier",
        "property_count", "vehicle_count", "aircraft_count", "vessel_count", "pep_status", "pep_level",
        "is_sanctioned", "sanctions_lists", "adverse_media_score", "adverse_media_count", "is_deceased",
        "date_of_death", "cause_of_death", "data_completeness_pct", "last_full_enrichment_at",
    ]
    for col in person_new_cols:
        op.drop_column("persons", col)

    for table in [
        "travel_history", "analyst_assessments", "timeline_events",
        "military_records", "corporate_directorships", "professional_licenses",
        "shell_company_links", "adverse_media", "pep_classifications",
        "ip_intelligence", "email_intelligence", "phone_intelligence",
        "vessels", "aircraft", "vehicles",
        "property_mortgages", "property_valuations", "property_ownership_history", "properties",
    ]:
        op.drop_table(table)
